import React from "react";

const ADD_ORDER = "ADD_ORDER";
const UPDATE_ORDER = "UPDATE_ORDER";
const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";
const UPDATE_ORDER_ITEM = "UPDATE_ORDER_ITEM";
const UPDATE_PERSON = "UPDATE_PERSON";
const INIT_ORDER = "INIT_ORDER";
const UPDATE_CONTRACTOR = "UPDATE_CONTRACTOR";
const INIT_CONTRACTOR = "INIT_CONTRACTOR";
export {
    ADD_ORDER,
    UPDATE_ORDER,
    ADD_ORDER_ITEM,
    DELETE_ORDER_ITEM,
    UPDATE_ORDER_ITEM,
    UPDATE_PERSON,
    INIT_ORDER,
    UPDATE_CONTRACTOR,
    INIT_CONTRACTOR
}